spin_manifest_version = "1"
authors = ["Uffe Hansen <uffe.hansen@gmail.com>"]
description = ""
name = "powerdata"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "powerdata"
source = "target/wasm32-wasi/release/powerdata.wasm"
allowed_http_hosts = []
[component.trigger]
route = "/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
