spin_manifest_version = "1"
authors = ["Uffe Hansen <uffe.hansen@gmail.com>"]
description = "Powerdata handler"
name = "powerdata"
trigger = { type = "http", base = "/powerdata" }
version = "0.1.0"

[[component]]
id = "customer-powerdata"
sqlite_databases = ["default"]
source = "customer-powerdata/target/wasm32-wasi/release/customer_powerdata.wasm"
allowed_http_hosts = []
[component.trigger]
route = "/customer/api"
[component.build]
command = "cargo build --target wasm32-wasi --release"
workdir = "customer-powerdata"
watch = ["src/**/*.rs", "Cargo.toml"]

