spin_manifest_version = "1"
authors = ["Uffe Hansen <uffe.hansen@gmail.com>"]
description = "Powerdata handler"
name = "powerdata"
trigger = { type = "http", base = "/powerdata" }
version = "0.1.0"

[[component]]
id = "customer-powerdata"
sqlite_databases = ["default"]
source = "customer-powerdata/target/wasm32-wasi/release/customer_powerdata.wasm"
allowed_http_hosts = []
[component.trigger]
route = "/customer"
[component.build]
command = "cargo build --target wasm32-wasi --release"
workdir = "customer-powerdata"
watch = ["src/**/*.rs", "Cargo.toml"]

[[component]]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.0.3/spin_static_fs.wasm", digest = "sha256:38bf971900228222f7f6b2ccee5051f399adca58d71692cdfdea98997965fd0d" }
id = "customer-component-ui"
files = [ { source = "assets", destination = "/" } ]
[component.trigger]
route = "/ui/..."
